name: 🚀 FTP Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload site to cPanel via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📤 Upload with SamKirkland FTP Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: ./
          local-dir: ./
          exclude: |
              .git/
              .github/
              .ftpignore
