name: 🚀 FTP Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload site to cPanel via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📤 Upload via FTP
        uses: lukaszraczylo/ftp-action@v1
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          remoteDir: /public_html/
          localDir: ./
          options: "--delete"
